# This workflow handles general unit testing of code
# using poetry and pytest for the project
name: Pytest and Unit test

# This workflow is callable from other workflows
on:
  workflow_call:

jobs: 
  python-style:
    name: Python Style 
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.0.1
      
      - name: Install dependencies
        working-directory: API
        run: poetry install

      - name: Run flake8
        working-directory: API
        run: poetry run pytest
